---
ID: "16ffb5b5-68c2-4020-b0a2-f2967e255cbf"
Parent: "6c34d0a4-d158-4449-b834-6433f38d1f5a"
Template: "0bae2cbd-33f5-4212-83f8-d63ad3c945a4"
Path: /sitecore/content/Trelleborg/Group/Home/Product and Solution
DB: master
SharedFields:
- ID: "db51d4e9-c24d-4670-af0e-62c8aa08e2b6"
  Hint: LocalData
  Value: "{D9AFCEB1-9F7A-437A-A9D4-89BAD538D928}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{68CA6F5E-AD94-4DEB-9AA8-F5BAF97CE6AA}"
              p:before="*"
              s:id="{2E991AA4-4B08-43D2-AD2B-17C11E69A499}"
              s:par="ListSignature&amp;PageSize&amp;Offset&amp;GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;FieldNames&amp;Styles&amp;SourceType=%7B90105CB9-2CFD-4151-9FA8-6CDF92B158C2%7D&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
              s:ph="main" />
            <r
              uid="{69DFD0DC-9831-46EB-A41F-D659E44447D7}"
              p:after="r[@uid='{68CA6F5E-AD94-4DEB-9AA8-F5BAF97CE6AA}']"
              s:ds="local:/Data/count"
              s:id="{5B249C53-F580-4623-8613-3AF9614126FE}"
              s:par="GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier"
              s:ph="main" />
            <r
              uid="{F7F1440A-2B42-4C39-BFCE-E2097A65FF33}"
              p:after="*[1=2]"
              s:ds="local:/Data/search"
              s:id="{FAE0D244-55C1-4F1B-8ED5-590C9F131CEE}"
              s:par="GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;SearchSignature&amp;FieldNames=%7BA24D0097-56EE-4437-98F0-6AB03EE3437A%7D&amp;Styles&amp;Reset Caching Options&amp;Scope=%7BC7CA9964-3520-49A3-94E6-850830A503C1%7D&amp;PageSize=20&amp;DefaultLanguageFilter=%7B04C9B082-DE71-4035-8D16-737BF024FDE6%7D&amp;DefaultSortOrder=%7BCDF44186-7AEF-49E9-AE00-137988698491%7D&amp;AutoFireSearchWhenNoCriteriaSet=1&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
              s:ph="main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190903T092901Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product and Solution
    - ID: "58aebef9-88b0-4c86-8907-12a78a1533f7"
      Hint: Title
      Value: Product and Solution
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
