---
ID: "12433817-b925-4829-8ae8-846938fdb00f"
Parent: "bcbb33e1-fe37-4db4-9480-f3c94520bc9f"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Trelleborg/Global/Presentation/Rendering Variants/ArticleList/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{2EDD1E7C-547E-4CD0-85BD-889AB772792A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191119T174919Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
