---
ID: "c9e4e4ff-da33-47a5-8a09-a44d1e3bbfa1"
Parent: "f1184c70-c3ae-4b21-84a9-b9282b82a9f5"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Themes/Trelleborg/Mitas Moto/Mitas/sass/base
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T063530Z
