---
ID: "a83ac698-6c6f-482b-b984-c19c8cd0c4bc"
Parent: "4640b0df-44a6-441a-b5ed-f28496af0436"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Trelleborg/Wheels/Presentation/Rendering Variants/Link List/Default
DB: master
BranchID: "60ac3def-7cda-406b-8f40-4e4f0073e4c2"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{C5678F86-D23D-41CA-B236-A1989FCFDAC7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190828T113632Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
