---
ID: "39281bcf-a4b2-4ff9-a903-667bb3c4e85e"
Parent: "751b5533-a3b6-47a4-b8c3-defe01fd68ee"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Trelleborg/Mitas Moto/Presentation/Rendering Variants/RichText/Default
DB: master
BranchID: "e4acb01a-2a91-4200-b9ce-205b2a5aa488"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{8F3094F8-34E0-4B48-913C-0DE361D3FBD9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190828T124254Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
