---
ID: "677aa223-44ab-4cec-b7e2-66b712f411f7"
Parent: "9d9ad06e-a139-4079-872d-a00b5f169fea"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Trelleborg/CustomNavigation/Default Breadcrumb Variant/$name/Default
DB: master
SharedFields:
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: "navigation-title"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160817T110201Z
