---
ID: "3b37752f-75e8-4390-9c22-1d0a4915fbeb"
Parent: "f682c1fe-347d-455e-87e2-3f2244a0e2be"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Themes/Trelleborg/Brand/TrelleborgBrandTheme/sass/base
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T063530Z
