---
ID: "a86f4193-a6dd-4c0c-a50c-2dee43aa4084"
Parent: "9b009205-b2c1-49d2-b9ac-d32818ac699a"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Trelleborg/Global/Presentation/Rendering Variants/GenericMediaElement/Default
DB: master
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{29592D34-AE20-4497-A046-F8C9D3FF2DAD}" />
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{D70DE426-6835-4947-A269-0F7EB025FE93}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191024T140415Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
