---
ID: "b5ecda8e-26bd-4f89-bd68-67d8d9df9418"
Parent: "6acc768d-02cf-41c3-8241-4bebcdd868c4"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Trelleborg/Global/Presentation/Rendering Variants/Sectionintro/Default
DB: master
BranchID: "cb2eab27-e28e-44bf-94f1-0ee9a327414b"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{193ADDAE-37B6-4DE2-A52F-943BBB1B3851}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191119T171902Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
