---
ID: "a60f47b8-d4ab-4341-9c43-f9d8e5048360"
Parent: "e4a64b3b-bb15-4bff-bc34-36dfa98f97b8"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Trelleborg/Media/Default MultiLanguage YouTube List Variant/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160817T085911Z
