---
ID: "ca4a02f2-1ffc-42f9-a466-0861f58c7417"
Parent: "c9326ca7-bf82-4121-a8bb-b8b336cbcadb"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: "/sitecore/media library/Foundation/Trelleborg/Icons/product-white-icon-6"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/1008E0027B4A4DAC936CBADCDD84AA1F.ashx?h=16&thn=1&w=16"
- ID: "22eac599-f13b-4607-a89d-c091763a467d"
  Hint: Width
  Value: 18
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "5d73ac5c-1a5d-4cce-ae20-6dde1dc73acf"
  Value: iVBORw0KGgoAAAANSUhEUgAAABIAAAAZCAYAAAA8CX6UAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAD1SURBVHgBzZXhDYJADIV7TnAjsIGM4AauwAaOgBvIBsoITuCNABNwG+gG2IbXeFzEhDt/8JKmOWi/NFxpzcii7/JsL/iezRlj3EIsmQB0C57bwMoILnEtQ/2MNEL0Q/z6wNawDQgXX64GRfHn8aNDMgg5FdKebEUyCHkNUq+5IIuKRHZHieJbk9bocKySQdAdfp8L8vBl8jcSyY3p7eVWpLL/AtFmQBbebwakE6DPBR3hXc6/pj00yDmnohq+VXLKPDqF1awGYXRcgnFbrALJfGarg/nzmEFoeYuIpEcKmPaLo2mDxLEzUCxP016T4aV7rVuIpTeTDw4pLtky8wAAAABJRU5ErkJggg==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 352
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/png
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: png
- ID: "cb09946f-3218-4823-87d2-d5007c199a96"
  Hint: Dimensions
  Value: 18 x 25
- ID: "de2ca9e4-c117-4c8a-a139-1ff4b199d15a"
  Hint: Height
  Value: 25
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191128T110140Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
