---
ID: "d4b0d9d9-36d0-4af7-8120-ce28cf2a90d9"
Parent: "c9326ca7-bf82-4121-a8bb-b8b336cbcadb"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: "/sitecore/media library/Foundation/Trelleborg/Icons/product-grey-icon-3"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/3F3F2F30DDEE4AABAF8ADC65CA01FFF1.ashx?h=16&thn=1&w=16"
- ID: "22eac599-f13b-4607-a89d-c091763a467d"
  Hint: Width
  Value: 31
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "004d5af1-b1d4-44a0-8d20-46954afe3ca6"
  Value: iVBORw0KGgoAAAANSUhEUgAAAB8AAAAmCAYAAAA820BcAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAIXSURBVHgB7VhNa8JAEN3ERDGCPdjSoulBobbVQwtGRaXgD+iP9uBFRbDXHopghJbqoV4sGrVvqpaCSXbjF4XmgcSQt/tmd3ZnZldigiiVSmHLsq4VRTnHq2rHkSRpOJvNeo1GwxTpUxIhFYvFaCAQMCBuapr2UqvVLDtePp+/UFU1I8uyWa/Xn3n9csVpxHiU5/N5CyMa8fi5XE4NhUIPMPSp2WwO3bgypy8G0RimciAiTGi321MShnvSPC5XfLFYxMiXzANg7AjtojweV3wb0OiZw6I8uLgofHFf3Bc/CqRCoUARLOxEQJjU8X08nU49RTkkl3uE5o4bR8FPR8bS0PnYjjCZTD7ZMgGdMm/ilBcc29CgSJxica/VagnlYFEgG+ros+P23V/tvvj/Eacgc4d9fsn+IgzDSMHAJPMI7ONHHkfmdBBGHX6FmUmvSui9gufzMlsWgirCpVGtVhV2DPFKpZLF42e0iNMnCMPcWnxncRyPdIht+BmHgRSORHtbnBvi5FtMcdapAbJRZl/+txv52s9O+PY/OwYoDpAbmEfsvNUODZGDooW9rjEPoPM8XPPB43HFUb+9YoslvexxGJtEuzceL8Aj9Pv9cTweJ96NruvvpmlaTlwyMJFI3GK2zmBAp9vtzt36FroWIWDhpanow9+xXbEZDAaV1UXCEFcnHaerk63EfxlhW2pD2IpEIgMR0TW+ADbUvKIGwiHqAAAAAElFTkSuQmCC
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 642
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/png
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: png
- ID: "cb09946f-3218-4823-87d2-d5007c199a96"
  Hint: Dimensions
  Value: 31 x 38
- ID: "de2ca9e4-c117-4c8a-a139-1ff4b199d15a"
  Hint: Height
  Value: 38
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191128T110135Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
