---
ID: "cd831fc9-d46d-43fc-b366-a9eead8db7c5"
Parent: "3875165a-f679-4c52-849e-25d35fb7ed45"
Template: "3875165a-f679-4c52-849e-25d35fb7ed45"
Path: /sitecore/templates/Project/Trelleborg/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190828T104752Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
