---
ID: "776d2d3c-55d9-407c-932f-ae5c2a5f6637"
Parent: "a898496d-d670-4701-88ac-aaa57479dad4"
Template: "a898496d-d670-4701-88ac-aaa57479dad4"
Path: /sitecore/templates/Feature/Trelleborg/Tables/Product Icons Bar/Product Icon/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191130T060448Z
    - ID: "46c6eeb9-7004-4c09-8634-107050c9248f"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
