---
ID: "a18d05ca-6269-40c3-bba2-41ee71925b60"
Parent: "7b0ffb86-14b1-4ec9-a062-2ab08d164d26"
Template: "7b0ffb86-14b1-4ec9-a062-2ab08d164d26"
Path: /sitecore/templates/Project/Trelleborg/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190828T104749Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
