---
ID: "6f60eae7-aed2-4222-a065-2fca9097b3db"
Parent: "19b280f6-f334-4995-8dbc-974fae0f87a8"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Trelleborg/Global/TrelleborgBaseTheme/gulp/serverConfig
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/6F60EAE7AED24222A0652FCA9097B3DB.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "3141c1e4-d467-4df4-8cd2-cd6f232d41ab"
  Value: eyJzZXJ2ZXJPcHRpb25zIjp7InByb2plY3RQYXRoIjoiXFxUaGVtZXNcXFRyZWxsZWJvcmdcXEdsb2JhbCIsInRoZW1lUGF0aCI6IlxcVHJlbGxlYm9yZ0Jhc2VUaGVtZSJ9fQ==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 100
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/octet-stream"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: json
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170707T125230Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
