---
ID: "1c7ea1ef-f936-488a-8da2-f0ac3138c388"
Parent: "bf4f7475-183c-4d17-93ca-15485d5878b6"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Trelleborg/Global/Presentation/Rendering Variants/LiteratureList/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{A728CC6A-37E0-45CA-8C49-58DD6D5BE28E}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191117T132752Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
