
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.FieldExtensions.ImageUrl(Sitecore.Data.Fields.ImageField)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.FieldExtensions.ImageUrl(Sitecore.Data.Fields.ImageField,Sitecore.Resources.Media.MediaUrlOptions)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.ItemExtensions.Url(Sitecore.Data.Items.Item,Sitecore.Links.UrlOptions)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.ItemExtensions.ImageUrl(Sitecore.Data.Items.Item,Sitecore.Data.ID,Sitecore.Resources.Media.MediaUrlOptions)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.ItemExtensions.ImageUrl(Sitecore.Data.Items.MediaItem,System.Int32,System.Int32)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.ItemExtensions.LinkFieldUrl(Sitecore.Data.Items.Item,Sitecore.Data.ID)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.ItemExtensions.GetLinkFieldUrl(Sitecore.Data.Fields.Field)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.ItemExtensions.ImageFieldUrl(Sitecore.Data.Items.Item,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.NVelocity.FieldTokens.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3995:URI return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Trelleborg.Foundation.SitecoreExtensions.NVelocity.FieldTokens.GetLinkUrl(Sitecore.Data.Items.Item,System.String)~System.String")]

