---
ID: "2a918323-0cc3-4213-a8b6-9db298f5f7c1"
Parent: "5088278e-9646-4178-90c9-6fb6b77f146d"
Template: "5088278e-9646-4178-90c9-6fb6b77f146d"
Path: /sitecore/templates/Feature/Trelleborg/Media/YouTube/YouTube/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191114T113226Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
