---
ID: "2edd1e7c-547e-4cd0-85bd-889ab772792a"
Parent: "c0cb0b58-5d41-4ca8-ade5-a9885903a7cc"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Trelleborg/List/Default ArticleList Variant/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160427T134629Z
