---
ID: "e8663de2-ccb0-4afc-b2cc-e525d049afa4"
Parent: "96aa16e4-e45b-421c-892c-274002d81321"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Trelleborg/Context Selector/Default MarketSelector Variant/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160817T085911Z
