---
ID: "a8d5fe17-3607-4c27-b7b4-6cf2ba4ef132"
Parent: "a8b9e94b-fe0c-4603-b647-72233c7648b4"
Template: "a8b9e94b-fe0c-4603-b647-72233c7648b4"
Path: /sitecore/templates/Feature/Trelleborg/Promotional/Rendering Parameters/Twitter Widget/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T130349
