---
ID: "3cfc6ac6-0cf1-41be-b658-e854a8ba8b38"
Parent: "db7fc435-fb8a-4563-bf79-7f0324588d21"
Template: "db7fc435-fb8a-4563-bf79-7f0324588d21"
Path: /sitecore/templates/Feature/Trelleborg/MultiPromo/Rendering Parameters/MultiPromo/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T104300
