---
ID: "6fdfdc26-9339-4bc7-8991-18c120bc7a4d"
Parent: "a97518c4-7101-4d1e-9c36-4de0fc3ce668"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Trelleborg/Wheels/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190828T113445Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
