---
ID: "d7dcd1e9-ac9b-4670-b4c2-d9945cfb7e5d"
Parent: "a97518c4-7101-4d1e-9c36-4de0fc3ce668"
Template: "0339bac0-78c1-43c1-b930-f8c26a5fdf80"
Path: /sitecore/content/Trelleborg/Wheels/Presentation/Placeholder Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190828T113443Z
