---
ID: "a00c3a76-35b6-4d01-becc-e3b878d2fe6e"
Parent: "f13eeae4-98bf-48b1-b9d8-69ff6575fbed"
Template: "f13eeae4-98bf-48b1-b9d8-69ff6575fbed"
Path: /sitecore/templates/Feature/Trelleborg/Media/Rendering Parameters/YouTube/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T104300
