---
ID: "29debebc-a886-406a-b13f-90d9e6c5def1"
Parent: "bc04985f-6c19-4c18-b242-6a2a4f56bfd5"
Template: "bc04985f-6c19-4c18-b242-6a2a4f56bfd5"
Path: /sitecore/templates/Feature/Trelleborg/Context Selector/MarketSelector/MarketSelectorCountry/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191015T083129Z
    - ID: "39bb9f84-afe4-44e6-a293-68337fd39792"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
